services:
  - type: web
    name: diabetes-predictor
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run new_copy.py --server.port=$PORT --server.enableCORS=false"

