services:
  - type: web
    name: diabetes-streamlit-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run new_copy.py --server.port $PORT --server.address 0.0.0.0
    plan: free
